### ISSUE TITLE
Support cockroach db metadata in ActiveRecordSubscriber

### ISSUE THREAD

**Issue by sl0thentr0py** [getsentry/sentry-ruby#2110]
We use the cockroachdb

Gem: https://github.com/cockroachdb/activerecord-cockroachdb-adapter

database.yml
```
development:
  adapter: cockroachdb
  host: foo.bar.local
  database: dev_db
  user: root
  port: 26257
  pool: 25
  disable_cockroachdb_telemetry: true
```

docker-compose.yml
```
version: "2"
services:
  db:
    image: cockroachdb/cockroach:v22.2.10
    command: start-single-node --insecure
    ports:
      - "26257:26257"
      - "8081:8080"
    volumes:
      - database:/cockroach/cockroach-data
      
volumes:
  database:
```

_Originally posted by @Piioo in https://github.com/getsentry/sentry-ruby/issues/2109#issuecomment-1725879544_
