### ISSUE TITLE
Support extracting timezone out of crontab in sidekiq-scheduler

### ISSUE THREAD

**Issue by shalvah-gs** [getsentry/sentry-ruby#2187]
### Issue Description

Hi, just tried out the new auto-crons feature for Sidekiq scheduler. Are there any caveats around it? We have a bunch of running jobs (Rails), but only one shows up in Sentry.

We have a `sidekiq_scheduler.yml.erb`:

<details>

```yaml
process_webhook_requests:
  every: '15s'
  class: StagedWebhookRequestEnqueuerJob

call_status_refresher:
  every: '2h'
  class: CallStatusRefresherEnqueuerJob

delete_webhook_requests:
  cron: '0 21 * * * Europe/Berlin' # 9pm daily
  class: StagedWebhookRequestDeleterJob

process_scheduled_call_requests:
  cron: '*/1 * * * * Europe/Berlin' # Runs every 1 minute
  class: ScheduledCallRequestsProcessorJob
```

</details>

and we have this in our Sidekiq initializer:

<details>

```rb
if ENV.fetch('RUN_SIDEKIQ_CRON').to_bool && Sidekiq.server?
  Sidekiq.configure_server do |config|
    config.on(:startup) do
      scheduler_file_content = File.read(Rails.root.join('config/sidekiq_scheduler.yml.erb'))

      Sidekiq.schedule = YAML.safe_load(
        ERB.new(scheduler_file_content).result
      )

      Sidekiq::Scheduler.reload_schedule!
    end
  end
else
  Sidekiq::Scheduler.enabled = false
end
```

</details>

However, only one job shows up in the UI, after 18+ hours of running:

<img width="1036" alt="image" src="https://github.com/getsentry/sentry-ruby/assets/104110245/07f643f3-970a-4b9f-ace7-1cdf6fdc80b3">

I've checked the logs, and we have the "Injected Sentry Crons monitor checkins into ..." message for all four jobs. And I can also see the transport messages:

<img width="742" alt="image" src="https://github.com/getsentry/sentry-ruby/assets/104110245/f4425a13-9226-46f8-829b-1553e5aaac25">

which makes me wonder if this is a backend issue?

### Reproduction Steps

Add `config.enabled_patches += [:sidekiq_scheduler]`

We did not make any other changes to our individual jobs.

### Expected Behavior

Expected to see all check-ins in the UI

### Actual Behavior

Only saw the one with a schedule `every: 2h`.

### Ruby Version

3.2

### SDK Version

5.14.0

### Integration and Its Version

Rails, Sidekiq, all version 5.14.0

### Sentry Config

```rb

Sentry.init do |config|
  config.enabled_environments = %w[production]
  filterable_params = Rails.application.config.filter_parameters
  filter = ActiveSupport::ParameterFilter.new(filterable_params)
  config.before_send = lambda do |event, _hint|
    filter.filter(event.to_hash)
  end
  config.breadcrumbs_logger = [:active_support_logger]
  config.excluded_exceptions -= ['ActiveRecord::RecordNotFound']
  config.excluded_exceptions += ['Errors::ExpectedError']
  config.enabled_patches += [:sidekiq_scheduler]
end
```

**Comment by sl0thentr0py** [comment]
ok so @shalvah-gs 

```yml
rocess_webhook_requests:
  every: '15s'
  class: StagedWebhookRequestEnqueuerJob
```

will be rejected by the server because we only support from 1 minute onwards

and these
```yml
delete_webhook_requests:
  cron: '0 21 * * * Europe/Berlin' # 9pm daily
  class: StagedWebhookRequestDeleterJob

process_scheduled_call_requests:
  cron: '*/1 * * * * Europe/Berlin' # Runs every 1 minute
  class: ScheduledCallRequestsProcessorJob
```

might also be getting rejected because of the timezone stuff, I will have to check with the server folks and get back to you. EIther way, I think we should just support them if it's not already, so thanks for the feedback!
